### ISSUE TITLE
Вопрос по скрипту

### ISSUE THREAD

**Issue by PUKPUKer0** [snhplayer/GetCoursePythonDownloader#1]
Привет, работает ли скрипт если в курсе видео ссылкой на приватный вимео, там через реферер открывается только вимео ссылка, и в исходном коде нет .mp4 файла

**Comment by snhplayer** [comment]
Привет
С таким я не встречался, так что, к сожалению, помочь не могу. Попробуй написать в issue автору оригинального скрипта, если он добавит поддержку этого, то и я в скором времени обновлю скрипт.
