### ISSUE TITLE
Загрузка размеров сегментов

### ISSUE THREAD

**Issue by ddkedr** [snhplayer/GetCoursePythonDownloader#2]
Приветствую! Спасибо за скрипт, очень помогает и работает быстрее оригинального 👍

Вопрос по функции загрузки размеров сегментов. Зачем она и на что влияет?
Если запустить скрипт с выключенной функцией, то все просто начинает сразу грузиться и результат получаем быстрее :)

**Comment by snhplayer** [comment]
Привет
Рад слышать!
Сегменты для себя добавлял, чтобы проверять, что все грузится как надо ))
Оставил в релизе, мало ли кому-нибудь пригодится ещё...
Но если никто использовать не будет - удалю или сделаю, чтобы включалось только с аргументом определенным.
